Repository Git-For-Geeks/Machine-Learning-Projects, pull requests merged in 2022-10, with the labels that each got.

#2 Sansgupta25-titanic dataset
  TITANIC/Sansgupta25/titanic.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted

#4 Decision tree using ID3 algorithm
  Decision-Tree-creator/README.md
  Decision-Tree-creator/data.csv
  Decision-Tree-creator/decision-tree-creator.ipynb
Labels: git-for-geeks, hacktoberfest-accepted, hard

#10 Sansgupta25-Australian weather Prediction
  Australian Weather Prediction/Australian_Whether_Prediction.ipynb
Labels: git-for-geeks, hacktoberfest-accepted, hard

#11 Create: Facial expression recognition
  Face_Reaction/app.py
Labels: git-for-geeks, hacktoberfest-accepted, hard

#14 Sansgupta25-Gold Price Prediction
  Gold Price Prediction/Gold_Price_Prediction.ipynb
Labels: git-for-geeks, hacktoberfest-accepted, hard

#16 Sansgupta25-Credit Card Fraud Prediction
  Credit Card Fraud Prediction/Credit_Card_Fraud_Detection.ipynb
Labels: git-for-geeks, hacktoberfest-accepted, hard

#23 Sansgupta25-Customer_Segmentation
  Customer Segmentation/Customer_Segmentation.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted

#24 Sansgupta25-Medical Insurance Prediction
  Medical_Insurance_Cost_Prediction/Medical_Insurance_Cost_Prediction.ipynb
Labels: git-for-geeks, medium

#28 Sansgupta25-Cancer CLassification
  Cancer-Classification/Breast_Cancer_Classification.ipynb
Labels: git-for-geeks, medium

#29 Sansgupta25-Movie Recommendation System
  Movie_Recommendation_System/Movie_Recommendation_System.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted

#31 Sansgupta25-Dog vs Cat Classification
  Dog Vs Cat Classification/Dog_vs_Cat_Classification.ipynb
Labels: git-for-geeks, medium

#32 Sansgupta25-Spam mail prediction
  Spam_Mail_Prediction/Spam_Mail_Prediction.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted

#34 Rock Mine Prediction
  Rock and Mine Predictions/Rock_vs_Mine_Prediction.ipynb
Labels: git-for-geeks, medium, hacktoberfest-accepted

#36 Decision tree algorithm
  Decisin tree algorihm/Decision tree algorithm.ipynb
Labels: git-for-geeks, medium

#39 added candidate elimination algorithm
  Candidate elimination Algorithm/Data.csv
  Candidate elimination Algorithm/candidate-elimination.ipynb
Labels: git-for-geeks, medium

#40 Find S algorithm
  Find S algorithm/Find S algorithm.ipynb
Labels: git-for-geeks, medium

#43 [ADDED]: Digit Recognition Project
  Paint GUI and Digit Recognizer/GUI.py
  Paint GUI and Digit Recognizer/img/abc
  Paint GUI and Digit Recognizer/img/img_0.png
  Paint GUI and Digit Recognizer/img/img_0.pngimg_0.png
  Paint GUI and Digit Recognizer/mnist.h5
Labels: git-for-geeks, hacktoberfest-accepted, hard
